### PR TITLE
Handle need restart after installation for winget

### PR DESCRIPTION
**Pull request by panther7**
#625

Added some new texts, but question is, are we really need dialog?

@marticliment

### CODE REVIEW

**Comment by marticliment** [comment]
I think this dialogs might be a little bit intrusive, especially when bulk-updating packages

**Comment by panther7** [comment]
> I think this dialogs might be a little bit intrusive, especially when bulk-updating packages

I agree, but now, show "error" dialog.

Should I just rewrite it in a text message like "installed successfully"?

**Comment by marticliment** [comment]
The current behaviour is:
1. If failed, show a message.
2. If succeeded, throw a notification.

What I would do is change the text of that "{0} installation succeeded" for "A restart is required to finish {0} installation", as well as addding a visual indicator in the ui telling the user to restart its PC.

If you don't understand how the error message class works, (it is a little bit messy), just let me know and I'll implement this feature

**Comment by panther7** [comment]
Done, new strings:
- {action} was successfully!
- Restart your PC to finish installation

**Comment by marticliment** [comment]
image
image

I have added new restart icons, so it looks visually different

**Review by marticliment — APPROVED** [review]

**Pull request merged**
