### PR TITLE
Update dependency

### PR DESCRIPTION
**Pull request by Malus-risus**

### CODE REVIEW

**Comment by marticliment** [comment]
What does renovate.json do?

**Comment by Malus-risus** [comment]
> What does renovate.json do?



> What does renovate.json do?

Renovate.json is used for dependency updates and is now deprecated.

**Comment by marticliment** [comment]
And if it is deprecated shouldn't it be removed?

**Comment by Malus-risus** [comment]
> And if it is deprecated shouldn't it be removed?

okay

**Review by marticliment — APPROVED** [review]

**Pull request merged**
