### PR TITLE
Update icons and screenshots from the excel file

### PR DESCRIPTION
**Pull request by skanda890**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**
- [X] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [X] **Have you tested that the committed code can be executed without errors?**
- [X] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing, and testing code that does not even compile, breaks other features, or does not introduce any useful changes. Thank you for your understanding

-----

Update icons and screenshots from the excel file

-----

### CODE REVIEW

**Comment by skanda890** [comment]
Is this code fine?

**Comment by skanda890** [comment]
Click on Commits and the latest commit for seeing the files which have been changed.

**Comment by marticliment** [comment]
Please update the screenshots on the excel file. They will be loaded automatically onto GitHub

**Comment by flatron4eg** [comment]
@skanda890 you can find the info here - https://marticliment.com/wingetui/help/icons-and-screenshots/#about-icons

**Review by skanda890 — COMMENTED** [review]
The URLs are shorter than before and redirect to the same icon.

**Comment by marticliment** [comment]
Your changes were merged by #2121. There is no need to manually publish PRs

**Comment by skanda890** [comment]
> Your changes were merged by #2121. There is no need to manually publish PRs

Oh, okay.

**Pull request closed without merging**
