### PR TITLE
Very basic start

### PR DESCRIPTION
**Pull request by Atrejoe**

### CODE REVIEW

**Comment by Atrejoe** [comment]
This is a foot-on-the ground.

I have rewritten Persontest to use testcases, making it easier to pinpoint what scenario fails.
Next use, reusable testclasses to have scenario's as reusable data:

Example output in test window:
image

**Comment by marticliment** [comment]
This definitely looks way better and more scalable than the tests I had set up.
Thanks❤️

**Comment by Atrejoe** [comment]
I can get a few more set up and clean the projects a bit.On Apr 27, 2024 13:50, Martí Climent ***@***.***> wrote:
This definitely looks way better and more scalable than the tests I had set up.
Thanks❤️

**Comment by marticliment** [comment]
Thanks for your help @Atrejoe!

**Pull request merged**
