### PR TITLE
Several improvements to Spanish translation.

### PR DESCRIPTION
**Pull request by uKER**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**
- [x] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [ ] **Have you tested that the committed code can be executed without errors?**

-----

Updated Spanish translation. Added several missing keys. Updated terminology to be more friendly to both Spain and Latin America. Made tone consistently "tuteo". Changed several main screen texts from imperative to infinitive. Fixed several mistakes and typos.

-----

### CODE REVIEW

**Comment by marticliment** [comment]
Hello @uKER,

I will merge this PR, but please follow the guide on [how to contribute to translations](https://github.com/marticliment/WingetUI/wiki#translating-wingetui), because if not integration breaks.

Thank you!

**Comment by uKER** [comment]
Oh, sorry about that.
I just signed up at Tolgee with this address ***@***.***)
Can you hook me up?
I just saw that the changes are already live, and noticed there's a couple more that aren't entirely right, and there's a couple non-translated strings in the About page.



________________________________
De: Martí Climent ***@***.***>
Enviado: jueves, 12 de octubre de 2023 15:53
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


Hello @uKER<https://github.com/uKER>,

I will merge this PR, but please follow the guide on how to contribute to translations<https://github.com/marticliment/WingetUI/wiki#translating-wingetui>, because if not integration breaks.

Thank you!

**Comment by marticliment** [comment]
GitHub is censoring your email

**Comment by uKER** [comment]
Huh? What do you mean?
I just logged in with no issue.
What error are you getting exactly?


________________________________
De: Martí Climent ***@***.***>
Enviado: viernes, octubre 13, 2023 8:42:06 a. m.
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


GitHub is censoring your email

**Comment by marticliment** [comment]
I cannot see your personal email if you post it here, github blocks it

image

**Comment by uKER** [comment]
Oh.
It's uker at outlook.com

________________________________

**Comment by marticliment** [comment]
You will receive an email from the Tolgee Platform with an invitation link! (Please check your spam folder)
 
Thank you!

**Comment by uKER** [comment]
I'm already in!
Cheers!
________________________________

**Comment by uKER** [comment]
Hey there!
I just submitted some more corrections.
That said, there's still this text in the About screen that doesn't seem to be internationalized, as I'm not seeing it in Tolgee.
________________________________
De: Martí Climent ***@***.***>
Enviado: viernes, 13 de octubre de 2023 9:03
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


You will receive an email from the Tolgee Platform with an invitation link! (Please check your spam folder)

Thank you!

**Comment by marticliment** [comment]
Which string do you mean?

Translations do get updated automatically in 24/48h

**Comment by uKER** [comment]
I attached a screenshot in my previous email.
________________________________
De: Martí Climent ***@***.***>
Enviado: viernes, 13 de octubre de 2023 15:03
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


Which string do you mean?

Translations do get updated automatically in 24/48h

**Comment by marticliment** [comment]
Email-attached screenshots are not recognized by github. they must be uploaded direclty on GH

**Comment by uKER** [comment]
https://i.imgur.com/DZWVzek.jpg
[https://i.imgur.com/DZWVzek.jpg]

________________________________
De: Martí Climent ***@***.***>
Enviado: viernes, 13 de octubre de 2023 15:11
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


Email-attached screenshots are not recognized by github. they must be uploaded direclty on GH

**Comment by marticliment** [comment]
They are now on Tolgee

**Comment by uKER** [comment]
And translated.
________________________________
De: Martí Climent ***@***.***>
Enviado: viernes, 13 de octubre de 2023 15:24
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


They are now on Tolgee

**Comment by uKER** [comment]
Here's some more non-internationalized strings.
https://i.imgur.com/YI9OKzN.png
[https://i.imgur.com/YI9OKzN.png]

________________________________
De: Martí Climent ***@***.***>
Enviado: viernes, 13 de octubre de 2023 15:24
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


They are now on Tolgee

**Comment by marticliment** [comment]
Those ones are not translatable yet

**Comment by uKER** [comment]
Hey! Just saw the latest changes made it into the app.
I just submitted 3 very minor changes, but I think it's looking real good now.
BTW, is there any chance I can get my name listed among the contributors?
Cheers!
________________________________
De: Martí Climent ***@***.***>
Enviado: sábado, 14 de octubre de 2023 11:23
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


Those ones are not translatable yet

**Comment by marticliment** [comment]
Hello @uKER,

You can add your name or github username on a special entry. It used to appear at the top, but it seems as if it broke. Please search for "{0} {0} {0}" and you will find it.

**Comment by uKER** [comment]
Well, I added myself to that one but that does not look like the list shown in the About dialog.
Am I doing anything wrong?
________________________________
De: Martí Climent ***@***.***>
Enviado: lunes, 16 de octubre de 2023 10:16
Para: marticliment/WingetUI ***@***.***>
Cc: uKER ***@***.***>; Mention ***@***.***>
Asunto: Re: [marticliment/WingetUI] Several improvements to Spanish translation. (PR #1488)


Hello @uKER<https://github.com/uKER>,

You can add your name or github username on a special entry. It used to appear at the top, but it seems as if it broke. Please search for "{0} {0} {0}" and you will find it.

**Comment by marticliment** [comment]
> Well, I added myself to that one but that does not look like the list shown in the About dialog.

This list will only be updated on the readme, and will be updated on WingetUI on the next version:
image

**Pull request merged**
