### PR TITLE
Use PySide translations for native elements

### LINKED ISSUE #527: [BUG/ISSUE] Translatable contextmenu
Original issue: #487

ContextMenu, probably need some translation for PySide

### PR DESCRIPTION
**Pull request by panther7**
Fix #527 

Maybe need more improvements for other langauges.

### CODE REVIEW

**Comment by marticliment** [comment]
Great!

I didn't have time to take a look at it yet.

I'll see how can this be integrated with tolgee and i''l merge that

**Comment by panther7** [comment]
I think, that is not compatible with Tolgee.

This is "native" Qt laguages file inside PySide.

**Comment by marticliment** [comment]
Yeah, but I maybe can get a python script to extract some keys from the jsons and to create native qt lang files

**Comment by panther7** [comment]
Could you merge this? It's first step for using PySide translation for native elements.

@marticliment

**Review by marticliment — APPROVED** [review]

**Pull request merged**
