### PR TITLE
Fix for Accent Color Change Theme bug

### PR DESCRIPTION
**Pull request by raghavdhingra24**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**
- [x] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [x] **Have you tested that the committed code can be executed without errors?**

-----
Hi there,
Accent color change in QT>=6.5 makes windows title bar go back to light mode and no method is currently available to prevent this - See: https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5. This code is currently hacky and sometimes fails to work or cause a flicker.

Video:
| Before | After |
| --- | --- |
| https://github.com/marticliment/WingetUI/assets/106472154/2ff63f61-b449-497a-ac45-7a9d59bce2c9 | https://github.com/marticliment/WingetUI/assets/106472154/eec61ccc-ad3a-465e-b510-78c3e4634a5f | 
| |Updated Video: https://github.com/marticliment/WingetUI/assets/106472154/13621319-1909-406b-893a-3940562d6ec0 |

Some other ways to reduce currently occurring problems -
1) We can increase the timeout to 2000ms or 3000ms for waiting for qt to finish changing the theme - decreases failure but causes the app show light mode for longer time.
2) Set app style to `None` - can have some unwanted behavior.

Thanks

Edit: Formatting
Edit2: Added updated video

### CODE REVIEW

**Comment by raghavdhingra24** [comment]
I have updated timer to wait for 3000ms. This makes the theme change back to selected one work most of the times.

Updated Video - 
https://github.com/marticliment/WingetUI/assets/106472154/13621319-1909-406b-893a-3940562d6ec0

**Comment by marticliment** [comment]
Seems fine until this bug gets fixed. 
When ready let me know to be able to merge.

Thanks!

**Comment by raghavdhingra24** [comment]
Checked on Windows 10 and the code is working correctly, ready to merge.

**Review by marticliment — APPROVED** [review]

**Comment by marticliment** [comment]
I have done my testing and it appears to work fine.

Thank you!

**Pull request merged**
