### PR TITLE
Draft: Improvements

### PR DESCRIPTION
**Pull request by panther7**

### CODE REVIEW

**Review by marticliment — APPROVED** [review]

**Comment by panther7** [comment]
This was draft... need fix translation rot/link in app :D

**Comment by marticliment** [comment]
Sorry, didn't see I'm gonna revert that then

**Comment by marticliment** [comment]
Now you should be able to reopen the PR, can you?

**Comment by panther7** [comment]
i cant :)

**Comment by marticliment** [comment]
Oh, i'm sorry, it was my fault.

Next time could you please mark them as draft PRs (i didn't read the title with enough attention), so my brain doesn't messes thigs up?

Thanks and sorry!

**Pull request merged**
