### PR TITLE
panther7 suggestion + rename Available Updates to Software Updates

### LINKED ISSUE #558: Discussion in commit
I've created this just to help track the discussion in https://github.com/marticliment/WingetUI/commit/4aa210bbfe7a2837369ccd14c3797372cbf6caa9

I've commited the suggested change to https://github.com/ppvnf/WingetUI/tree/patch-44

### PR DESCRIPTION
**Pull request by ppvnf**
Captura de tela 2022-12-30 061623

closes #558

### CODE REVIEW

**Comment by panther7** [comment]
You can squash into one commit.

**Comment by ppvnf** [comment]
I don't know how

**Comment by panther7** [comment]
Try, learn, example via `git rebase -i main`

> https://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Review by marticliment — APPROVED** [review]

**Comment by ppvnf** [comment]
Thanks! I am gonna take a look on that so I don't make the same mistake next time!

**Pull request merged**
