### PR TITLE
Adds additional description to package manager toggles

### LINKED ISSUE #2103: [ENHANCEMENT] Explain what the Package Manager setting does
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Add explanatory text to the Package Managers area in Settings which defines its scope, and optionally add a fuller explanation to Help.

### Describe how this improvement could help users.

Currently there is no explanation as to what the radio buttons in this section do. An explanatory scope should be added to make it clear whether this affects some or all of the WingetUI features e.g. if I turn off Npm am I turning off updates, or discovery, or everything?

### PR DESCRIPTION
**Pull request by turw41th**
Adds additional descriptive text to settings page according to request #2103.

- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**
- [x] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [x] **Have you tested that the committed code can be executed without errors?**
- [x] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the time of the contributors, who have to spend their free time reviewing, fixing and testing code that does not even compile, breaks other features or does not introduce any useful changes. Thank you for your understanding

From what I have understood, it is not necessary to specifically link the text to some property in order to be properly translatable. If this is indeed needed, please let me know.

Relates to #2103

### CODE REVIEW

**Comment by marticliment** [comment]
Yes, in the translation part you are correct.

Can you please share a screenshot of how the changes are shown?

**Comment by turw41th** [comment]
image

It will look like this. I was experimenting with different font sizes and thought this to look best,

**Comment by marticliment** [comment]
I have two propositions:
 - What about setting its opacity to 50~80%? It will show kinda greyed out, which is the style to follow on informational texts such as this one.
 - Wouldn't it be better to remove the abbreviation (you'll -> you will)? IMO it would look more formal to not have the contraction, what do you think?

**Comment by turw41th** [comment]
- Alright I'll play with the opacity a little bit and see what looks best, I'll share another screenshot and push the changes when I'm happy with it.
- I'm not a native English speaker myself and I'd agree with you that such abbreviations can look informal, although I think the specific one I've used is pretty much accepted in all circumstances by now. I can change it though and then see how that looks.

**Comment by turw41th** [comment]
@marticliment Changed the stuff. This is how it looks with 70% which looked best to me:

image

**Review by marticliment — APPROVED** [review]

**Pull request merged**
