### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by panther7**
ref #529

### CODE REVIEW

**Comment by panther7** [comment]
Done, check it, if tis ok for you.

@marticliment

**Comment by ppvnf** [comment]
Would it be possible to do this automatically to all translators (or at least the ones that have a Github account)?

**Comment by panther7** [comment]
@marticliment Please try this fix [f20cb99](https://github.com/marticliment/WingetUI/pull/531/commits/f20cb99122580a68f677c87d429f9a9dc2080e97) for ISS.

**Comment by panther7** [comment]
@ppvnf I can't check, if "name" is github accout. You can add "@" prefix for your name/nick and link will be created.

**Comment by marticliment** [comment]
> @marticliment Please try this fix [f20cb99](https://github.com/marticliment/WingetUI/pull/531/commits/f20cb99122580a68f677c87d429f9a9dc2080e97) for ISS.

It seems to work for me. Thank you!

P.D. I can merge that, right?

**Comment by panther7** [comment]
Yes, u can

**Comment by ppvnf** [comment]
I've tested it and it works great. Thanks! Is there a simple way using Tolgee for @marticliment to add the other translators as contributors so they also have their Github profiles linked? Also, should I manually link my profile in the readme?

**Comment by panther7** [comment]
Links from translators is not secured, I think, this is good solution ;-)

**Comment by marticliment** [comment]
> I've tested it and it works great. Thanks! Is there a simple way using Tolgee for @marticliment to add the other translators as contributors so they also have their Github profiles linked? Also, should I manually link my profile in the readme?

Every contributor will need to add their username instead of their name

I'll add the ability to show also links in the readme (id you were to link that manually, it would get erased after the readme was generated again)

**Pull request merged**
